name: nuikta-build
on:
  push:
    branches:
      - "build"
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04 # python 3.11 libssl problem
            ename: main.bin
            # uname: updater.bin
            esuffix: ""
            platform: "linux"
          # - os: macos-latest
          #   ename: main.bin
          #   uname: updater.bin
          #   esuffix: ""
          #   platform: "darwin"
          #   nuitka-nofollow-import-to: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.9
          architecture: "x64"
      - name: Install dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libbz2-dev zlib1g-dev libffi-dev liblzma-dev libexpat1-dev patchelf git
      - name: Install dependencies
        if: runner.os == 'macOS'
        run: |
          brew install patchelf git
      - name: install nuitka
        if: runner.os == 'Linux'
        run: |
          pip install nuitka==2.3.11
          python -m nuitka --version
      - name: Build python script into a stand-alone exe
        run:
          python -m nuitka --standalone --output-dir=o --nofollow-import-to=requests,async_timeout,Pillow,pilmoji,yaml,tgcrypto,apscheduler,email,emoji,loguru,websockets,tzlocal,PILpkg_resources,pyrogram,geoip,encodings,google-re2,asyncio,aiohttp,aiohttp_socks,cryptography,addons main.py
        shell: bash
      - name: Process linux python dependencies files
        if: runner.os != 'Windows'
        shell: bash
        run: |
          cp -r ${{ env.pythonLocation }}/lib/python3.11/* o/main.dist/
          mv o/main.dist/lib-dynload/_sqlite3.*.so o/main.dist/
          mv o/main.dist/lib-dynload/pyexpat.*.so o/main.dist/
      - name: install App dependencies
        if: runner.os != 'Windows'
        shell: bash
        run: |
          pip install -r requirements.txt -t o/main.dist/
      - name: Remove some packages
        shell: bash
        run: |
          rm -r o/main.dist/turtle* || true
          rm -r o/main.dist/importlib || true
          rm -r o/main.dist/encodings || true
          rm -r o/main.dist/pydoc_data || true
          rm -r o/main.dist/ensurepip || true
          rm -r o/main.dist/ctypes/test || true
          rm -r o/main.dist/distutils || true
          rm -r o/main.dist/tkinter || true
          rm -r o/main.dist/unittest || true
          rm -r o/main.dist/lib2to3 || true
          rm -r o/main.dist/setuptools || true
          rm -r o/main.dist/idlelib || true
          rm -r o/main.dist/lib-dynload || true
          rm -r o/main.dist/site-packages || true
          rm -r o/main.dist/test || true
          rm -r o/main.dist/config-3.11* || true
          rm -r o/main.dist/__pycache__ || true

      - name: Run UPX
        if: runner.os != 'macOS'
        uses: crazy-max/ghaction-upx@v3
        with:
          files: |
            o/main.dist/${{ matrix.ename }}
          args: -q
      - name: change permission
        if: runner.os != 'Windows'
        run: |
          chmod +x o/main.dist/${{ matrix.ename }}
      - name: Compress Folder
        if: runner.os != 'Windows'
        run: |
          mv o/main.dist/${{ matrix.ename }} o/main.dist/koipy${{ matrix.esuffix }}
          cd o/main.dist/
          file=koipy-${{ matrix.platform }}-amd64.zip
          zip -r $file ./*
          mv $file ../
          cd ../../
      #          cp o2/updater.dist/${{ matrix.uname }} o/main.dist/
      #          mv o/main.dist/${{ matrix.uname }} o/main.dist/updater${{ matrix.esuffix }}
#      - name: Upload Artifact
#        if: startsWith(github.ref, 'refs/tags/')
#        uses: actions/upload-artifact@v3
#        with:
#          name: koipy-${{ matrix.platform }}-amd64
#          path: o/koipy-${{ matrix.platform }}-amd64.zip
#          retention-days: 1

#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#        if: runner.os == 'linux'

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: o/koipy-${{ matrix.platform }}-amd64.zip
          tag_name: v1.0.0


  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            files: |
              o/main.dist/main.exe
            args: -q
            ename: main.exe
            uname: updater.exe
            esuffix: ".exe"
            platform: "windows"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.9
          architecture: 'x64'
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
      - uses: Nuitka/Nuitka-Action@main
        with:
          script-name: main.py
          mode: standalone
          output-dir: o
          nofollow-import-to: "requests,async_timeout,Pillow,pilmoji,yaml,tgcrypto,apscheduler,email,emoji,loguru,websockets,tzlocal,PIL,pkg_resources,pyrogram,geoip,encodings,google-re2,asyncio,aiohttp"


      - name: Process some files
        if: runner.os == 'Windows'
        run: |
          Move-Item -Path o/main.dist/main.exe -Destination o/main.dist/koipy.exe
          Copy-Item -Recurse -Path ${{ env.pythonLocation }}\Lib\* -Destination o\main.dist\
          Copy-Item -Recurse -Path ${{ env.pythonLocation }}\DLLs\_overlapped.pyd -Destination o\main.dist\
          Copy-Item -Recurse -Path ${{ env.pythonLocation }}\DLLs\pyexpat.pyd -Destination o\main.dist\
          pip install -r requirements.txt -t o/main.dist/
        shell: pwsh
      - name: Remove some packages
        if: runner.os == 'Windows'
        run: |
          Remove-Item -Recurse -Path o/main.dist/turtle*  
          Remove-Item -Recurse -Path o/main.dist/importlib
          Remove-Item -Recurse -Path o/main.dist/encodings 
          Remove-Item -Recurse -Path o/main.dist/pydoc_data
          Remove-Item -Recurse -Path o/main.dist/ensurepip
          Remove-Item -Recurse -Path o/main.dist/ctypes/test
          Remove-Item -Recurse -Path o/main.dist/distutils
          Remove-Item -Recurse -Path o/main.dist/tkinter
          Remove-Item -Recurse -Path o/main.dist/unittest
          Remove-Item -Recurse -Path o/main.dist/lib2to3
          Remove-Item -Recurse -Path o/main.dist/idlelib  
          Remove-Item -Recurse -Path o/main.dist/site-packages
          Remove-Item -Recurse -Path o/main.dist/test
          Remove-Item -Recurse -Path o/main.dist/config-3.11* 
          Remove-Item -Recurse -Path o/main.dist/__pycache__
          Remove-Item -Recurse -Path o/main.dist/setuptools

        shell: pwsh
      - name: mkdir dist-info floder
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          cd o/main.dist/
          ../../.github/scripts/move-dist-info.ps1
          cd ../../

      - name: Run UPX
        if: runner.os != 'macOS'
        uses: crazy-max/ghaction-upx@v3
        with:
          files: |
            o/main.dist/koipy.exe
          args: -q
      - name: Compress Folder
        if: runner.os == 'Windows'
        run: |
          cd o/main.dist/
          $FolderToCompress = "."
          $ZipFileName = "koipy-${{ matrix.platform }}-amd64.zip" 
  
          Write-Host "Compressing folder: $FolderToCompress"
          Compress-Archive -Path $FolderToCompress -DestinationPath $ZipFileName -Force
  
          if (Test-Path $ZipFileName) {
            Write-Host "Successfully created: $ZipFileName"
          } else {
            Write-Host "Failed to create zip file"
          }
          mv $ZipFileName ..
          cd ../../
        shell: pwsh
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: koipy-${{ matrix.platform }}-amd64
#          path: o/main.dist/koipy-${{ matrix.platform }}-amd64.zip
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v4
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: |
#            ${{ secrets.DOCKERHUB_USERNAME }}/koipy:windows-amd64
#          platforms: windows/amd64
#
#      - name: Logout from Docker Hub
#        run: docker logout

#      - name: Upload artifact
#        if: runner.os != 'Windows'
#        uses: actions/upload-artifact@v4
#        with:
#          name: koipy-${{ matrix.platform }}-amd64
#          path: o/main.dist/

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: o/koipy-${{ matrix.platform }}-amd64.zip
          tag_name: v1.0.0
